# Copyright 2024-, European Centre for Medium Range Weather Forecasts.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import glob
import os

import matplotlib.pyplot as plt
from matplotlib import font_manager

from earthkit.plots import styles
from earthkit.plots.components.figures import Figure
from earthkit.plots.components.maps import Map
from earthkit.plots.components.subplots import Subplot
from earthkit.plots.definitions import DEFAULT_STYLES_DIR, FONTS_DIR
from earthkit.plots.quickplot import quickplot
from earthkit.plots.schemas import schema
from earthkit.plots.shortcuts import timeseries
from earthkit.plots.styles import Style
from earthkit.plots.temporal.timeseries import TimeSeries

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = [
    "Figure",
    "Subplot",
    "Map",
    "Style",
    "schema",
    "styles",
    "quickplot",
    "timeseries",
    "TimeSeries",
]


def _register_fonts():
    """Register bundled fonts with matplotlib's font manager."""
    fontpaths = glob.glob(os.path.join(FONTS_DIR, "*"))
    for fontpath in fontpaths:
        font_files = glob.glob(os.path.join(fontpath, "*.ttf"))
        for font_file in font_files:
            font_manager.fontManager.addfont(font_file)


def _register_styles():
    """Register bundled .mplstyle files with matplotlib's style library."""
    import matplotlib

    for mplstyle in DEFAULT_STYLES_DIR.glob("*.mplstyle"):
        rc = matplotlib.rc_params_from_file(str(mplstyle), use_default_template=False)
        plt.style.core.library[mplstyle.stem] = rc
    plt.style.core.available[:] = sorted(plt.style.core.library.keys())


_register_fonts()
_register_styles()
