# Copyright 2024-, European Centre for Medium Range Weather Forecasts.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import dataclasses
import glob
import os

import matplotlib
import matplotlib.pyplot as plt

from earthkit.plots import frames, styles
from earthkit.plots.frames import Batch, Browser
from earthkit.plots.components.figures import Figure
from earthkit.plots.components.subplots import Subplot
from earthkit.plots.definitions import DEFAULT_STYLES_DIR, FONTS_DIR
from earthkit.plots.namespaces import climatology, geo, timeseries
from earthkit.plots.quickplot import quickplot
from earthkit.plots.schemas import schema
from earthkit.plots.styles import Style
from earthkit.plots.styles.auto import list_styles, load_style

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


__all__ = [
    "Batch",
    "Browser",
    "frames",
    "Figure",
    "Subplot",
    "Map",
    "Style",
    "load_style",
    "list_styles",
    "schema",
    "styles",
    "geo",
    "timeseries",
    "TimeSeries",
    "climatology",
    "Climatology",
    "quickplot",
]


# The default style sheet uses Roboto. The bundled Roboto faces are registered
# under this private family name so they cannot be shadowed by a system-installed
# Roboto (e.g. the ``fonts-roboto`` package on Linux). When both are present and
# share the same family/weight/style, matplotlib's font scorer breaks the tie by
# registration order, which is non-deterministic across platforms and cache
# states and causes rendering (and image-test) differences. A private family name
# guarantees the bundled faces always win.
BUNDLED_FONT_FAMILIES = {"Roboto": "Roboto (earthkit-plots)"}


def _register_fonts():
    """Register bundled fonts with matplotlib's font manager.

    Fonts in folders listed in :data:`BUNDLED_FONT_FAMILIES` are registered under
    a private family name (see the note on that mapping) so the bundled faces are
    never shadowed by identically-named system fonts.
    """
    fontpaths = glob.glob(os.path.join(FONTS_DIR, "*"))
    for fontpath in fontpaths:
        private_family = BUNDLED_FONT_FAMILIES.get(os.path.basename(fontpath))
        font_files = glob.glob(os.path.join(fontpath, "*.ttf"))
        for font_file in font_files:
            if private_family is None:
                matplotlib.font_manager.fontManager.addfont(font_file)
                continue
            # Register under a private family name, preserving the face's real
            # weight/style so weight-specific requests still resolve correctly.
            # FontEntry is a frozen dataclass, so build a renamed copy.
            entry = matplotlib.font_manager.ttfFontProperty(matplotlib.font_manager.ft2font.FT2Font(font_file))
            entry = dataclasses.replace(entry, name=private_family)
            matplotlib.font_manager.fontManager.ttflist.append(entry)


def _register_styles():
    """Register bundled .mplstyle files with matplotlib's style library."""
    for mplstyle in DEFAULT_STYLES_DIR.glob("*.mplstyle"):
        rc = matplotlib.rc_params_from_file(str(mplstyle), use_default_template=False)
        plt.style.library[mplstyle.stem] = rc
    plt.style.available[:] = sorted(plt.style.library.keys())


_register_fonts()
_register_styles()


def __getattr__(name):
    if name == "Map":
        from earthkit.plots.components.maps import Map

        return Map
    if name == "TimeSeries":
        from earthkit.plots.temporal.timeseries import TimeSeries

        return TimeSeries
    if name == "Climatology":
        from earthkit.plots.temporal.climatology import Climatology

        return Climatology
    raise AttributeError(f"module 'earthkit.plots' has no attribute {name!r}")
