build:
  modules:
  - ninja
  dependencies:
  - ecmwf/ecbuild@develop
  - MathisRosenhauer/libaec@master
  - ecmwf/eccodes@develop
  - ecmwf/eckit@develop
  - ecmwf/odc@develop
  python_dependencies:
  - ecmwf/eccodes-python@develop
  - ecmwf/cfgrib@master
  - ecmwf/pdbufr@master
  - ecmwf/pyodc@develop
  env:
  - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
  - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
  parallel: 64
  requirements: tests/downstream-ci-requirements.txt