build:
  modules:
  - ninja
  dependencies:
  - ecmwf/ecbuild@develop
  - MathisRosenhauer/libaec@refs/tags/v1.1.3
  - ecmwf/eccodes@develop
  - ecmwf/eckit@develop
  - ecmwf/odc@develop
  - ecmwf/metkit@develop
  - ecmwf/fdb@develop
  python_dependencies:
  - ecmwf/eccodes-python@develop
  - ecmwf/cfgrib@master
  - ecmwf/pdbufr@master
  - ecmwf/pyodc@develop
  - ecmwf/pyfdb@develop
  env:
  - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
  - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
  - GITHUB_WORKFLOW=anything
  parallel: 64
  requirements: tests/downstream-ci-requirements.txt
  pytest_cmd: |
      make unit-tests
      make image-tests